version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@1.0.1
jobs:
  build_backend:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd backend
      - run: npm install
workflows:
  heroku_deploy:
    jobs:
      - build_backend
      - heroku/deploy-via-git
